services:
  app:
    image: ertusharmodi/managehub-vcard:latest
    container_name: managehub-vcard-app
    restart: unless-stopped
    expose:
      - "80"
    env_file:
      - .env
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_CONNECTION: mongodb
      DB_HOST: mongodb
      DB_PORT: 27017
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_URI: mongodb://mongodb:27017
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - app_storage:/var/www/html/storage
    networks:
      - managehub-network

  nginx:
    image: nginx:1.27-alpine
    container_name: managehub-vcard-nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Nginx config folder
      - ./nginx-conf:/etc/nginx/conf.d:ro
      # SSL Certificates (Yahan se Nginx ko files milengi)
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - managehub-network

  mongodb:
    image: mongo:7
    container_name: managehub-vcard-mongodb
    restart: unless-stopped
    command: ["--bind_ip_all"]
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - managehub-network

networks:
  managehub-network:
    driver: bridge

volumes:
  mongo_data:
  app_storage:
